[package]
name = "sa-token-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Core library for sa-token-rust, a powerful authentication and authorization framework"

[dependencies]
sa-token-adapter = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
jsonwebtoken = { workspace = true }
sha2 = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
urlencoding = { workspace = true }
hex = "0.4.3"
getrandom = { workspace = true }
base64 = { workspace = true }
argon2 = { workspace = true }
hmac = { workspace = true }
md-5 = { workspace = true }
sha1 = { workspace = true }
data-encoding = { workspace = true }
reqwest = { workspace = true, optional = true }

[dev-dependencies]
sa-token-storage-memory = { workspace = true }

[features]
default = []
fory = ["sa-token-adapter/fory"]
sso-http = ["dep:reqwest"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
